# Generated by Django 4.2.4 on 2023-11-14 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='co_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
