# Generated by Django 4.2.4 on 2023-11-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0006_alter_community_co_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='module_it_belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mgt_app.module'),
        ),
    ]
