# Generated by Django 4.2.4 on 2023-11-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0009_alter_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
