# Generated by Django 5.0 on 2023-12-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0013_studentquizmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_number',
            field=models.PositiveIntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
