# Generated by Django 5.0 on 2023-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0016_quiz_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Dead', 'Dead')], db_default=models.Value('Dead'), max_length=200),
        ),
    ]
