# Generated by Django 5.0 on 2023-12-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0018_alter_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizmark',
            name='final_score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
