# Generated by Django 5.0 on 2023-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgt_app', '0022_assignment_mode_of_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='student_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
